name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    jobs:
    build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup jfrog
      uses: jfrog/setup-jfrog-cli@v3
      with:
          version: latest
      env:
          JF_URL: ${{ secrets.VINCEURL }}
          JF_USER: ${{ secrets.VINCEUSER }}
          JF_ACCESS_TOKEN: ${{ secrets.VINCETOKEN_JF }}
    - name: archive creatio
      run: |
        jf rt u "**" generic-lovcal/Vince.zip --archive zip --include-dirs |
        jf rt bp generic_local/Vince.zip
   
